inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
RSpec/ScatteredSetup:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/valkyrie/specs/**/*'
    - 'Rakefile'
    - '*.gemspec'
Style/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
    - 'valkyrie-storage-s3.gemspec'
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Style/PredicateName:
  Exclude:
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
