---
version: '3.4'
volumes:
  localstack:
services:
  localstack:
    image: localstack/localstack
    ports:
      - 4572:4572
    environment:
      SERVICES: s3
    healthcheck:
      test:
      - CMD
      - curl
      - "-f"
      - http://127.0.0.1:4572/
      interval: 30s
      timeout: 5s
      retries: 3
